import dayjs from "dayjs";
export default class Helper {
  // Generated By Chat GPT

  static getWeekRange(date = new Date()) {
    const day = date.getDay(); // Sunday = 0, Monday = 1, ..., Saturday = 6
    const diffToMonday = day === 0 ? -6 : 1 - day; // shift Sunday back to previous Monday
    const startOfWeek = new Date(date);
    startOfWeek.setDate(date.getDate() + diffToMonday);
    startOfWeek.setHours(0, 0, 0, 0); // start of the day

    const endOfWeek = new Date(startOfWeek);
    endOfWeek.setDate(startOfWeek.getDate() + 6);
    endOfWeek.setHours(23, 59, 59, 999); // end of the day
    const formatDate = (d) => d.toISOString().split("T")[0]; // YYYY-MM-DD
    return {
      startOfWeek: formatDate(startOfWeek),
      endOfWeek: formatDate(endOfWeek),
    };
  }

  static getDurationInHrs(start, end) {
    const format = "h:mm A";
    const startTime = dayjs(start, format);
    let endTime = dayjs(end, format);

    // Handle overnight time span
    if (endTime.isBefore(startTime)) {
      endTime = endTime.add(1, "day");
    }

    const totalMinutes = endTime.diff(startTime, "minute");
    const decimalHours = (totalMinutes / 60).toFixed(2); // Keep 2 decimal places
    return parseFloat(decimalHours);
  }

  static getDateRange(startDate, endDate) {
    const dayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

    const current = new Date(startDate);
    current.setHours(0, 0, 0, 0);

    const end = new Date(endDate);
    end.setHours(0, 0, 0, 0);

    const formatDate = (d) => {
      const year = d.getFullYear();
      const month = String(d.getMonth() + 1).padStart(2, "0");
      const day = String(d.getDate()).padStart(2, "0");
      return `${year}-${month}-${day}`;
    };

    const dates = [];

    while (current <= end) {
      dates.push({
        date: formatDate(current),
        day: dayNames[current.getDay()],
      });
      current.setDate(current.getDate() + 1);
    }
    return dates;
  }
}
