export default class Helper {
  // Generated By Chat GPT

  static getWeekRange(date = new Date()) {
    const day = date.getDay(); // Sunday = 0, Monday = 1, ..., Saturday = 6
    const diffToMonday = day === 0 ? -6 : 1 - day; // shift Sunday back to previous Monday
    const startOfWeek = new Date(date);
    startOfWeek.setDate(date.getDate() + diffToMonday);
    startOfWeek.setHours(0, 0, 0, 0); // start of the day

    const endOfWeek = new Date(startOfWeek);
    endOfWeek.setDate(startOfWeek.getDate() + 6);
    endOfWeek.setHours(23, 59, 59, 999); // end of the day
    const formatDate = (d) => d.toISOString().split("T")[0]; // YYYY-MM-DD
    return {
      startOfWeek: formatDate(startOfWeek),
      endOfWeek: formatDate(endOfWeek),
    };
  }

  static getDateRange(startDate, endDate) {
    const dayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

    const current = new Date(startDate);
    current.setHours(0, 0, 0, 0);

    const end = new Date(endDate);
    end.setHours(0, 0, 0, 0);

    const formatDate = (d) => d.toISOString().split("T")[0]; // YYYY-MM-DD

    const dates = [];

    while (current <= end) {
      dates.push({
        date: formatDate(current),
        day: dayNames[current.getDay()],
      });
      current.setDate(current.getDate() + 1);
    }
    return dates;
  }
}
